### ISSUE TITLE
ArrayOfType

### ISSUE THREAD

**Issue by jonassix** [wojtpl2/ExtendedXmlSerializer#206] opened 2018-09-19 08:11 UTC
Hi,

I want to deserialize a List. This is my xml structure

```
<?xml version="1.0" encoding="UTF-8"?>
<ArrayOfTravelFile>
     <TravelFile>
           ....
     </TravelFile>
</ArrayOfTravelFile>

```

My class is named TravelFile And i try to deserialize like this.

```
var serializer = new ConfigurationContainer().Create();
var a = serializer.Deserialize<List<TravelFile>>((xml));

```

I tried different approaches, including implementing a custom serializer how ever, i keep running against the same error.
``System.InvalidOperationException: 'An attempt was made to load a type with the fully qualified name of 'ArrayOfTravelFile', but no type could be located with that name.'``
Note : I have no problems deserializing with the standard xmlserializer. I want to use this framework so i can my classes more pocco and have issues with badly formatted datetimes and floats/doubles.
The xml data is provided by a third party.

Thank you for your help and advice

**Comment by Mike-EEE** [comment] 2018-09-19 11:37
Wow @jonassix thanks for writing in and reporting this.  I took some time to check this out and I am indeed surprised that this doesn't work as we do have `EnableClassicMode` which is supposed to be conformant for scenarios such as these.

We could (and should) provide this functionality for classic mode, but doing so now will break those who are using it.  That is, currently classic mode is serializing objects with `Array` (that is, the default behavior) and if we change it, those who are using it will stop working.

We could add a new extension method called `EnableClassicModeNaming` that adds a new extension that addresses this.  This is probably the best path as it doesn't introduce a breaking change for those who are using existing functionality.

I am open to further ideas/discussion around this.

The GOOD news, however, is that if you are just looking to read files, it turns out you can hardwire the functionality you are looking for right now.  Check it out:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/6af21181441cd7921340c8227f4efea42611ffd1/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue206Tests.cs#L16-L22

We have `Array` and `IList` hardwired for v2, unfortunately.  Not ideal but timelines had to be met. 😆  I will see if I can get the added functionality in there for the other parts, but let me know how this treats you in the meantime.

**Comment by Mike-EEE** [comment] 2018-09-19 12:28
Ah here's a mention of `EnableImplicitTyping`:
https://github.com/wojtpl2/ExtendedXmlSerializer#implicit-namespacestyping

If this case we're not exactly using it as what that was designed for, but that's OK. 😆

You will have to add other types that are used as well, so `Participant`:
```
new ConfigurationContainer().EnableImplicitTyping(typeof(TravelFile[]), typeof(TravelFile), typeof(Participant))
```

We also offer type locators that you can use to find all types in an assembly/namespace:

```
new ConfigurationContainer().EnableImplicitTyping(new PublicTypesInSameNamespace<TravelFile>())
```

**Comment by jonassix** [comment] 2018-09-19 12:51
This unfortunatly does not work. 
          ```
  var support = new ConfigurationContainer()
                                          //.EnableImplicitTyping(typeof(TravelFile[]), typeof(TravelFile))
                                          //.EnableImplicitTyping(new PublicTypesInSameNamespace<TravelFile>())
                                          .EnableImplicitTyping(typeof(TravelFile[]), typeof(TravelFile), typeof(Participant))
                                          .Type<TravelFile[]>()
                                          .Name("ArrayOfTravelFile")
                                          .Create();

            var t = support.Deserialize<TravelFile[]>(xml);
```

It remains null. 

Also i wil convert this code to be able to handle all of my classes using generics. not just TravelFile. 
So this means i'll have to use reflections to find all parameters and then add them as type param in the EnableImplicitTyping part.
It's okay if i have to do this but i'm a bit supprised. 

the function .EnableImplicitTyping(new PublicTypesInSameNamespace<TravelFile>() also has no effect.

Anyway much appreciated for your help with my issue.

**Comment by Mike-EEE** [comment] 2018-09-19 13:04
>It's okay if i have to do this but i'm a bit supprised. 

Ah ok I am a little confused here.  Are you saying you are wanting to deserialize generic types? That isn't supported by the classic serializer as far as I know.  Or is that why you are here? 😂

As for your problem with serialization, let's see if you can spot the problem:

```
<Participants>
         <Participant>
            <ParticipantId>679556</ParticipantId>
            <Name>xxxx</Name>
         </Participant>
         <Participant>
            <ParticipantId>679557</ParticipantId>
            <Name>xxx</Name>
      </Participants>
```

:)

I have also committed code with passing test demonstrating the type collection/builder as well. 👍

**Comment by Mike-EEE** [comment] 2018-09-19 13:12
Boooo... I got the wrong issue #!  here's the commit:
https://github.com/wojtpl2/ExtendedXmlSerializer/commit/e63b45c69ebf18a809fc934b097be45e73a4e39f

**Comment by jonassix** [comment] 2018-09-19 13:35
:p sure, i copy pasted it wrong. But i can assure you that's not the issue.

```
var types = new PublicNestedTypes<TravelFile>();
            var support = new ConfigurationContainer().EnableImplicitTyping(types.Concat(types.Select(x => x.MakeArrayType())))
                                                      .Type<TravelFile[]>()
                                                      .Name("ArrayOfTravelFile")
                                                      .Create();

            var a = support.Deserialize<TravelFile[]>(xml);
```

but now i receive the original exception again. I asume, my publicNestedTypes is wrong, because if drill through i get a count of 0

. 

With generics i meant, that i will create a Generic Deserialize method so i can define it's type at run time.

**Comment by Mike-EEE** [comment] 2018-09-19 14:35
Ah I see your pain @jonassix !

Check it out:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/efd659835fd9aace055aca90773e1d4654ddf066/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue206Tests.cs#L16-L36

BETTER ??? 😁

**Comment by Mike-EEE** [comment] 2018-09-19 14:36
FWIW you will have to try it from our preview feed here:
https://www.myget.org/F/wojtpl2/api/v3/index.json

**Comment by jonassix** [comment] 2018-09-19 15:05
Damn you work fast. Just tried it unfortunatly the same error. 

You are passing Issue206Tests instead of TravelFile as a type. That is something i cannot do. I only have type TravelFile. 

What am i doing wrong?

 ```
           var support = new ConfigurationContainer().EnableImplicitTypingFromPublicNested<TravelFile>().EnableClassicListNaming()
                                                      //.EnableImplicitTyping(typeof(TravelFile[]), typeof(Participant), typeof(Participant[]))
                                                      //.EnableImplicitTyping(types.Concat(types.Select(x => x.MakeArrayType())))
                                                      //.Type<TravelFile[]>()
                                                      //.Name("ArrayOfTravelFile")
                                                      .Create();

            var a = support.Deserialize<TravelFile[]>(xml);
```

`System.InvalidOperationException: 'An attempt was made to load a type with the fully qualified name of 'ArrayOfTravelFile', but no type could be located with that name.'

`

**Comment by Mike-EEE** [comment] 2018-09-19 16:43
Outside of a test environment it is different. :)  Try:

```
var support = new ConfigurationContainer().EnableImplicitTypingFromNamespace<TravelFile>().EnableClassicListNaming().Create();

           var a = support.Deserialize<TravelFile[]>(xml);
```

CROSSING FINGERS @jonassix 🤞😂

**Comment by jonassix** [comment] 2018-09-20 06:51
that works, but no participants.
I've added an xml file.

**Comment by jonassix** [comment] 2018-09-20 07:32
Here you can find the full class library.
[TravelNote.Migrator.Core.zip](https://github.com/wojtpl2/ExtendedXmlSerializer/files/2400170/TravelNote.Migrator.Core.zip)

**Comment by jonassix** [comment] 2018-09-20 07:34
you will see stuff like XmlStringDateOfBirth, that is to be able to handle badly formed datetimes.
One of the reasons i want to use this project 😋

**Comment by Mike-EEE** [comment] 2018-09-20 08:53
> One of the reasons i want to use this project

I feel your pain. 😆  So I am looking into this and the issue is that there are elements in the Xml which are not accounted for by the class definition.  For instance, `TravelFile` has a `FileStatus` which is not in the class definition.

We should totally handle this gracefully (and thought we did), but we do not at the moment.  I am looking into this now.  For the time being, however, ensure all properties are accounted for (they can be `string`) and see if it works for you.

**Comment by jonassix** [comment] 2018-09-20 09:36
in my class TravelFile, i have a Enum FileStatus, In The xml i have a string that matches the enum. 
How should i handle this?  
Maybe it's just me, but finding the correct info in the documention is not that easy 😄 



Thanks for looking in to this. Much appreciated.

**Comment by Mike-EEE** [comment] 2018-09-20 09:45
Ah!  No you're right.  I had it taken out on my side. :)  The enum should "just work"... 

Actually now looking at it, it should all work.  Let me look into this a little further and flesh out the model here and then update you.

**Comment by Mike-EEE** [comment] 2018-09-20 10:15
Alright, now I am really confused.  I was able to make this work with a passing test here:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/147ec024f50e211837c66fde6b3e403ed26fb865/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue206TestsExtensive.cs#L21-L115

The only thing I can think of is perhaps you have a cached assembly?  We have a deployment issue currently with #184.

Try deleting your local package cache for ExtendedXmlSerialier (e.g. `C:\Users\<user>\.nuget\packages`) and getting the latest from the preview feed.

**Comment by Mike-EEE** [comment] 2018-09-20 10:20
If you still cannot get it to work, please create a simple repo somewhere here on GitHub and I will then download and take a look into it.

**Comment by Mike-EEE** [comment] 2018-09-20 10:27
Ah!  Found it.  I actually had some elements removed.  There appears to be something with the Dates used.  Looking into this now.

**Comment by jonassix** [comment] 2018-09-20 10:56
Okay, Let me know if i still have to provide a repo.

**Comment by Mike-EEE** [comment] 2018-09-20 11:09
Ah no worries I believe it had to do with the Ignore attribute.  I've got
Real Life to attend to for a few hours here and I'll get back to it.
 We're close! Hang in the there!  😅

**Comment by Mike-EEE** [comment] 2018-09-20 14:13
WHEW... ok.  [I think I finally got it](https://i.kym-cdn.com/photos/images/original/000/954/660/350.jpg). 😛 

There was an issue with parsing null values which was not accounted for with our parsers.

I even got you local Xml `DateTime` parsing while I was at it.  Check it out:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/38208b3a2a476b99651227f41085c9b17119638d/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue206TestsExtensive.cs#L21-L25

Let me know how this works for you now. 👍

**Comment by Mike-EEE** [comment] 2018-09-20 14:16
Man that formatting looks nothing like my machine:

![](https://i.imgur.com/rOqY4PF.png)

**Comment by jonassix** [comment] 2018-09-20 15:13
Hmm, weird, i don't have DateTimeConverter. But i can see it in your repo. 
Am i missing a Library?

the only one i have is ExtendedXmlSerializer v2.1.8.0 , runtime version v4.0.30319

**Comment by jonassix** [comment] 2018-09-20 15:17
Lol, just saw in your source code that your class is not public. 
So i can't do Register(DateTimeConverter.Local)

**Comment by Mike-EEE** [comment] 2018-09-20 15:42
I hate to ask and I apologize as this is going to be an inconvenience between deployments here, but [did you try clearing out your cache](https://www.youtube.com/watch?v=nn2FB1P_Mn8)?  The problem is that if you have a 2.1.8 already on disk, and you get the "latest" from our preview feed, it says it gets it, but it's really not.  The reason why I suspect this is now the problem is [that DateTimeConverter is public now](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/ContentModel/Conversion/DateTimeConverter.cs).

**Comment by Mike-EEE** [comment] 2018-09-20 15:43
I guess I should say... every deployment made to our preview feed until we deploy 2.1.8 is going to say is 2.1.8 if that makes sense.

**Comment by jonassix** [comment] 2018-09-20 15:59
maybe, just did a reinstall. Perhaps there is some lag. Cause when i looked at the code. it was not public. 
now it is.
still dont have it though. instead of providing a repo. I've created a full project for you with your library. 
[TravelFileFormatGeneratorTEMP.zip](https://github.com/wojtpl2/ExtendedXmlSerializer/files/2402072/TravelFileFormatGeneratorTEMP.zip)

I used the nuget reinstall command.

**Comment by Mike-EEE** [comment] 2018-09-20 16:16
OH!  I totally forgot to leave out a verrrrrrrrrrrry important detail! Haha...

You need to update your class files.  You basically have to get rid of the attributes and all that DateTime handling :)

Check them out now:

```
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/38208b3a2a476b99651227f41085c9b17119638d/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue206TestsExtensive.cs#L151-L283
```

**Comment by jonassix** [comment] 2018-09-21 06:47
Alright. That works! Thanks man! And now i can begin using this library 👍

**Comment by Mike-EEE** [comment] 2018-09-21 11:47
Woohoo!  You have no idea how happy that makes me. 😆  That was a rough one!  But worth it.  I think the feeling was when we got v2 done that we wanted to cater to legacy scenarios but the focus was more on having an object-graph serializer that utilized the Xml format.  Now that the dust has settled a bit we're able to tackle these sorts of addendums, granted that they are easy enough to do. :)

I have pushed `2.1.9` with this feature and it should be visible on Nuget soon.  Please let me know if you run into any further issues!  Closing this one for now.

**Closed by Mike-EEE** 2018-09-21 11:47 UTC
Labels: Documentation, bug, discussion
