### ISSUE TITLE
Deserialize bug 2.0.0-alpha6

### ISSUE THREAD

**Issue by FaustoNascimento** [wojtpl2/ExtendedXmlSerializer#125] opened 2017-09-15 11:54 UTC
Imagine the following class:

    public class Person
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Nationality { get; set; }

        public bool Married { get; set; }
    }

When serializing the following `Person` ...

    var person = new Person{ FirstName = "John", LastName = "Doe" };
    serializer.Serialize(person);

The following XML is generated (more or less):

    <Person>
        <FirstName>John</FirstName>
        <LastName>Doe</LastName>
        <Married>false</Married>
    </Person>

And everything is OK with the world, deserializing works properly too etc etc.

But now imagine this scenario:

    var person = new Person{ FirstName = "John", LastName = string.Empty, Nationality = "British", Married = true };
    serializer.Serialize(person);

This will produce the following XML:

    <Person>
        <FirstName>John</FirstName>
        <LastName></LastName>
        <Nationality>British</Nationality>
        <Married>true</Married>
    </Person>

Which also looks exactly what it should like. However when I try to deserialize that... I end up with a `Person` where `LastName == string.Empty`, `Nationality == null` and `Married == false`

**Comment by Mike-EEE** [comment] 2017-09-26 14:27
Hey @FaustoNascimento thanks for reporting this. Apologies for the delay here as I have been on vacation.  I will make this a priority and will aim to look into this in the next day or so.

**Comment by Mike-EEE** [comment] 2017-09-26 21:19
OK this was due to how we're using the native `XmlReader` and extracting the value from that.  I have checked in a fix.  @wojtpl2 I noticed we haven't pushed Alpha 7 yet.  Were we supposed to?  I forget. 😆 Last I remember I was going to work on v2.0 documentation, which I hope to start up tomorrow and have done next week.

I am thinking we should get this fix in with an Alpha 7 push when you find the time. 👍

**Comment by FaustoNascimento** [comment] 2017-09-27 12:42
@Mike-EEE great that it's been fixed, but I'm curious why other properties of an object would also be set to null even if the XML says something else?

I mean I can understand a property of an object being set to its type's default value is the XML is empty, but why would this affect other properties in the object, even if the XML has "proper values" for it?

**Comment by FaustoNascimento** [comment] 2017-09-27 12:49
Also, how would your change in code account for manually generated XML where someone wrote something like:

`<Married/>`
or...
`<Married></Married>`
?

Bearing in mind that `Married` is a bool value it should default to `false`. Or an int... or any other object type that's either not nullable or is nullable but the default value is not a null.

Clearly if the XML is generated by the serializer this would never happen, but that doesn't make the XML above incorrect imho and you should account for situations where the user has written the XML by hand.

**Comment by wojtpl2** [comment] 2017-09-27 13:23
It should work in the same way like in standard `XMLSerializer`.

**Comment by Mike-EEE** [comment] 2017-09-27 13:23
Ah fair questions.  I appreciate them. :)  In this case, we were running into an edge condition specifically with an empty string.  Basically when we were calling `XmlReader.Read`, it would end up calling it twice in the case of an empty string, instead of once.  This would essentially forward the cursor on the document graph one extra position, and throw the rest of the reading off for the remainder of the graph.  This is why values didn't materialize properly after this value.

As for the default values, the `<Married />` should default to false, and `<Married></Married>` should throw an error, as you are essentially aiming to construct a boolean from an empty string (not supported by default framework internals).

So the important part being here, the issue is more of an `XmlReader` positioning than a value materialization, if that makes sense.

**Comment by Mike-EEE** [comment] 2017-09-27 13:39
Agreed, @wojtpl2 ... The conversion code is intact from v1, so that should all still work as expected.  Unfortunately, I do not see the tests that I thought I had brought over from v1, so I will add a new issue to track this for v2 release.

As always, if something doesn't work as expected please let me know (preferably via PR/commit with broken test) and I will certainly look into it. 👍

**Comment by Mike-EEE** [comment] 2017-09-27 15:49
FWIW I was wrong about the `<Married />` tag example.  **All** empty tags with no values are treated the same, both in EXS and classic `XmlSerializer`.  That is, they all throw an `InvalidOperationException`.  I have added a test to our test suite to demonstrate/validate/verify this.

**Comment by FaustoNascimento** [comment] 2017-09-28 11:53
Understand this is different from what the `XmlReader`/`XmlSerializer` does, but would you consider adding something to ensure that when XML like `<Married />` or `<Married></Married>` is found and it can't cast into the desired type it just takes the type's default value (which it what already happens when the tag is not present, so basically this is just a change to say that instead of throwing an error it would take the type's default value).

I feel like this more accurately reflects what the XML is trying to represent. I mean, end of the day the XML is valid so throwing an error seems wrong...

**Comment by Mike-EEE** [comment] 2017-09-28 13:19
Ah!  No you are right.  This is a great opportunity for an extension.

Maybe something like `new ConfigurationContainer().EnableImplicitlyDefinedDefaultValues()` that would essentially catch the exception thrown and return the default value in this case.

I have captured this in #127.

**Comment by Mike-EEE** [comment] 2017-09-28 13:22
I have also just now pushed the changes for #127, so this is in the latest commit.  @wojtpl2, if @FaustoNascimento signs off on this, we can push Alpha 7. 👍

**Comment by Mike-EEE** [comment] 2017-10-03 16:47
I am going to assume that is a "yes" from @FaustoNascimento. :)  We will look into getting Alpha 7 pushed ASAP.

**Comment by Mike-EEE** [comment] 2017-10-18 19:14
This has been fixed in the latest versions.  Please feel free to comment on this issue (or open another issue) if there is any outstanding/expected work if not. Thanks again for your participation, @FaustoNascimento!

**Closed by Mike-EEE** 2017-10-18 19:14 UTC
Labels: bug
