### ISSUE TITLE
How can I serialize `Encoding` properties

### ISSUE THREAD

**Issue by johanvergeer** [wojtpl2/ExtendedXmlSerializer#253] opened 2019-07-04 07:47 UTC
I have a class that contains a `System.Text.Encoding` property

```csharp
public class ClassWithEncodingProperty
{
    public Encoding Encoding { get; set; }

    public ClassWithEncodingProperty()
    {
        this.Encoding = Encoding.Default;
    }
}
```

And a test to serialize this class:

```csharp
public class ClassWithEncodingPropertySpec
{
    [Fact]
    public void TestSerialize()
    {
        var c = new ClassWithEncodingProperty();

        var serializerContainer = new ConfigurationContainer()
            .ConfigureType<ClassWithEncodingProperty>();

        var serializer = serializerContainer.Create();

        var stream = new MemoryStream();

        using (var writer = XmlWriter.Create(stream))
        {
            serializer.Serialize(writer, c);
            writer.Flush();
        }

        stream.Seek(0, SeekOrigin.Begin);
        string contents = new StreamReader(stream).ReadToEnd();
    }
}
```

An exception is thrown when I try to serialize this class:

```
Message: System.InvalidOperationException : The serializer for type 'System.Text.SBCSCodePageEncoding' could not be found.  Please ensure that the type is a valid type can be activated. The default behavior requires an empty public constructor on the (non-abstract) class to activate.
```

Since 'System.Text.SBCSCodePageEncoding' is `internal` I can't create a, `IExtendedXmlCustomSerializer` directly, so I did the next best thing I could come up with and use `System.Text.Encoding`, which is the superclass of `SBCSCodePageEncoding`.

```csharp
public class EncodingSerializer : IExtendedXmlCustomSerializer<Encoding>
{
    public Encoding Deserialize(XElement xElement)
    {
        return Encoding.UTF8; // Needs to be replace with real deserialization once the error is gone.
    }

    public void Serializer(XmlWriter xmlWriter, Encoding obj)
    {
        xmlWriter.WriteString("Replace this with real encoding"); // Needs to be replaced with real serialization once the error is gone.
    }
}
```

And I registered the custom serializer in the `ConfigurationContainer`:

```csharp
public class ClassWithEncodingPropertySpec
{
    [Fact]
    public void TestSerialize()
    {
        var c = new ClassWithEncodingProperty();

        var serializerContainer = new ConfigurationContainer()
            .ConfigureType<Encoding>()
                .CustomSerializer(new EncodingSerializer())
            .ConfigureType<ClassWithEncodingProperty>();

            // Omitted for brevity
    }
}
```

But this still throws the same error. 

So how can I serialize this `internal` subclass.

**Comment by Mike-EEE** [comment] 2019-07-04 09:53
Hey good question @johanvergeer ... thank you for writing in and asking.  In the process of answering your question I found a bug so that's always a plus.

As for your line of thinking, you were close.  You can make a custom serializer as such:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/f7526ce6eb599828779f98347945cee63a8399d5/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue253Tests.cs#L46-L60

And then register it 1 of 2 ways (depending on if you like static type-checking on compile):

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/f7526ce6eb599828779f98347945cee63a8399d5/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue253Tests.cs#L17-L37

As I mentioned this will not work on the nuget, so if you want to give this a whirl, it is available on our preview feed here:

https://www.myget.org/F/wojtpl2/api/v3/index.json

If you have any further questions/issues please let me know and I will do my best to assist you. 👍

**Comment by johanvergeer** [comment] 2019-07-04 11:24
Hi @Mike-EEE ,

I just made the changes you suggested. I updated the NuGet package to v2.1.20, and created the serializer. 

It looks like the serialization passed, but when deserializing I get this exception:

```
ExtendedXmlSerializer.Core.Sprache.ParseException: 'An attempt was made to parse the identity 'https://extendedxmlserializer.github.io/system:SBCSCodePageEncoding', but no type could be located with that name.'
```

**Comment by Mike-EEE** [comment] 2019-07-04 12:53
Weird.  Can you post the XML that is generated?  Also, full stacktrace would be helpful as well.

**Comment by johanvergeer** [comment] 2019-07-04 13:53
Sure. Here is the generated XML:

This is generated from the class above, which works. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ClassWithEncodingProperty xmlns="clr-namespace:Common.Unittests.Serialization;assembly=Common.Unittests">
<Encoding exs:type="sys:SBCSCodePageEncoding" xmlns:exs="https://extendedxmlserializer.github.io/v2" xmlns:sys="https://extendedxmlserializer.github.io/system">1252</Encoding>
</ClassWithEncodingProperty>
```


This is generated from another (and bigger) class, which doesn't deserialize.

```xml
<?xml version="1.0" encoding="utf-8"?>
<Settings xmlns="clr-namespace:OurProject.Model;assembly=OurProject">
  <DbSettings xmlns:ns1="clr-namespace:OurProject;assembly=OurProject" xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="ns1:DBVCSV">
    <BestandsEncoding xmlns:sys="https://extendedxmlserializer.github.io/system" exs:type="sys:SBCSCodePageEncoding">1252</BestandsEncoding> 
  </DbSettings>
</Settings>
```

This is the full output from testrunner when I created the second xml snippet:

```
Test Name:	Company.Project.Common.Unittests.Serialization.SettingsSerializationSpec.SerializePrinterInstellingen
Test FullName:	Company.Project.Common.Unittests.Serialization.SettingsSerializationSpec.SerializePrinterInstellingen
Test Source:	C:\Workspace\Project\Company.Project.Common.Unittests\Serialization\SettingsSerializationSpec.cs : line 35
Test Outcome:	Failed
Test Duration:	0:00:05,07

Result StackTrace:	
bij ExtendedXmlSerializer.ContentModel.Reflection.TypePartReflector.Create(TypeParts parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Reflection\TypePartReflector.cs:regel 56
   bij System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   bij ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Core\Sources\CacheBase.cs:regel 51
   bij ExtendedXmlSerializer.ContentModel.Reflection.TypeParser.Create(String parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Reflection\TypeParser.cs:regel 45
   bij System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   bij ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Core\Sources\CacheBase.cs:regel 51
   bij ExtendedXmlSerializer.ContentModel.Reflection.ReflectionParser.Create(String parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Reflection\ReflectionParser.cs:regel 63
   bij System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   bij ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Core\Sources\CacheBase.cs:regel 51
   bij ExtendedXmlSerializer.ExtensionModel.Xml.FormatReaderContext.Get(String parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\FormatReaderContext.cs:regel 42
   bij ExtendedXmlSerializer.ExtensionModel.Xml.XmlReader.Get(String parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\XmlReader.cs:regel 51
   bij ExtendedXmlSerializer.ContentModel.Format.ParsedContent`1.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Format\ParsedContent.cs:regel 39
   bij ExtendedXmlSerializer.ContentModel.Format.ContextualReader`1.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Format\ContextualReader.cs:regel 40
   bij ExtendedXmlSerializer.ContentModel.DecoratedReader`1.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\DecoratedReader.cs:regel 49
   bij ExtendedXmlSerializer.ContentModel.Reflection.TypedParsingReader.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Reflection\TypedParsingReader.cs:regel 41
   bij ExtendedXmlSerializer.ContentModel.ConfiguredReader`1.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\ConfiguredReader.cs:regel 42
   bij ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:regel 35
   bij ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:regel 45
   bij ExtendedXmlSerializer.ContentModel.Reflection.Classification.FromAttributes(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Reflection\Classification.cs:regel 59
   bij ExtendedXmlSerializer.ContentModel.Reflection.Classification.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Reflection\Classification.cs:regel 53
   bij ExtendedXmlSerializer.ContentModel.Extensions.GetClassification(IClassification this, IFormatReader parameter, TypeInfo defaultValue) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Extensions.cs:regel 56
   bij ExtendedXmlSerializer.ExtensionModel.References.ReferenceReader.GetReference(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceReader.cs:regel 67
   bij ExtendedXmlSerializer.ExtensionModel.References.ReferenceReader.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceReader.cs:regel 72
   bij ExtendedXmlSerializer.ExtensionModel.References.ReferenceSerializer.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceSerializer.cs:regel 74
   bij ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:regel 35
   bij ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:regel 45
   bij ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializer.cs:regel 44
   bij ExtendedXmlSerializer.ContentModel.Members.MemberHandler.Handle(IInnerContent contents, IMemberSerializer member) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberHandler.cs:regel 37
   bij ExtendedXmlSerializer.ContentModel.Content.InnerContentServices.Handle(IInnerContent contents, IMemberSerializer member) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentServices.cs:regel 62
   bij ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.IsSatisfiedBy(IInnerContent parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberInnerContentHandler.cs:regel 50
   bij ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.Execute(IInnerContent parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberInnerContentHandler.cs:regel 59
   bij ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentReader.cs:regel 46
   bij ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:regel 35
   bij ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:regel 45
   bij ExtendedXmlSerializer.ExtensionModel.References.ReferenceReader.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceReader.cs:regel 76
   bij ExtendedXmlSerializer.ExtensionModel.References.ReferenceSerializer.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceSerializer.cs:regel 74
   bij ExtendedXmlSerializer.ContentModel.RuntimeSerializer.Get(IFormatReader reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\RuntimeSerializer.cs:regel 52
   bij ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:regel 35
   bij ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:regel 45
   bij ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializer.cs:regel 44
   bij ExtendedXmlSerializer.ContentModel.Members.MemberHandler.Handle(IInnerContent contents, IMemberSerializer member) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberHandler.cs:regel 37
   bij ExtendedXmlSerializer.ContentModel.Content.InnerContentServices.Handle(IInnerContent contents, IMemberSerializer member) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentServices.cs:regel 62
   bij ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.IsSatisfiedBy(IInnerContent parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberInnerContentHandler.cs:regel 50
   bij ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.Execute(IInnerContent parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberInnerContentHandler.cs:regel 59
   bij ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentReader.cs:regel 46
   bij ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:regel 35
   bij ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:regel 45
   bij ExtendedXmlSerializer.ExtensionModel.References.ReferenceReader.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceReader.cs:regel 76
   bij ExtendedXmlSerializer.ExtensionModel.References.ReferenceSerializer.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceSerializer.cs:regel 74
   bij ExtendedXmlSerializer.ContentModel.SerializerAdapter`1.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\SerializerAdapter.cs:regel 64
   bij ExtendedXmlSerializer.ExtensionModel.References.ReferenceAwareSerializers.Serializer.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceAwareSerializers.cs:regel 74
   bij ExtendedXmlSerializer.ExtensionModel.RootInstanceExtension.Serializer.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\RootInstanceExtension.cs:regel 61
   bij ExtendedXmlSerializer.ExtensionModel.References.CircularReferenceEnabledSerialization.Container.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\References\CircularReferenceEnabledSerialization.cs:regel 45
   bij ExtendedXmlSerializer.Read`1.Get(T parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Read.cs:regel 49
   bij ExtendedXmlSerializer.Serializer`2.Deserialize(TRead reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Serializer.cs:regel 44
   bij ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Deserialize(XmlReader reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\ExtendedXmlSerializer.cs:regel 42
   bij Company.Project.Common.Unittests.Serialization.SettingsSerializationSpec.SerializePrinterInstellingen() in C:\Workspace\Project\Company.Project.Common.Unittests\Serialization\SettingsSerializationSpec.cs:regel 124
Result Message:	ExtendedXmlSerializer.Core.Sprache.ParseException : An attempt was made to parse the identity 'https://extendedxmlserializer.github.io/system:SBCSCodePageEncoding', but no type could be located with that name.
```

**Comment by Mike-EEE** [comment] 2019-07-04 14:36
Bummer @johanvergeer I am having trouble reproducing this.  I did create a new test with the provided XML but it looks like I am missing something here:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/d937c74567adb36442391f56aff62fd1c3bbd2c2/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue253Tests.cs#L51-L64

Apologies for not being exact with my ask, but are you able to provide a simple C# class that reproduces this issue?  Feel free to also submit a PR with the new test I just created with the classes/code, ensuring the test fails with the error and I can take a look into that, as well.

(Or if copy/pasting code works better for you, that's fine, too).

**Comment by Mike-EEE** [comment] 2019-07-04 14:37
Oh, the other aspect I forgot to ask about: is there any further configuration that you are applying to the `ConfigurationContainer`?  That might be worth knowing, too.

**Comment by johanvergeer** [comment] 2019-07-05 12:40
I have not been able to reproduce it either. Very weird,
I did restart my computer, though.

**Comment by Mike-EEE** [comment] 2019-07-05 12:46
Cool!  It may be due to a caching issue, unfortunately.  We use the same moniker for both preview and public releases, and up the preview by one more than what has been published on the public feed (e.g. .20 on preview when public is .19 -- as it is now).

This seems to have addressed a lot of issues, but apparently there are some lurking issues still.  I might re-add this to the list of "things to try" going forward just in case.

**Comment by Mike-EEE** [comment] 2019-07-08 10:57
This has been deployed to Nuget:
https://www.nuget.org/packages/ExtendedXmlSerializer/

If you run into any additional problems please feel free to open a new issue.

Closing for now.

**Closed by Mike-EEE** 2019-07-08 10:57 UTC
Labels: Documentation, bug, question, sample code
