### ISSUE TITLE
Bad debug performance with circular references

### ISSUE THREAD

**Issue by thomasjoscht** [wojtpl2/ExtendedXmlSerializer#129] opened 2017-09-29 12:45 UTC
Hey, I encounter currently a performance limitation using ExtendedXmlSerilizer.csproj as project reference in my solution. There are thrown soooo many CircularReferencesDetectedException which are all logged in Visual Studio Debugger leading to incredible bad performance. My (extremely simplified) object graph looks like:

Class A
- Collection property of class B
- Collection property of class C

Class C
- Property of class B (reference)

My class A holds collection of objects of class B. Serializing class A will output this at top of XML. My class C holds a reference to object of class B which are collected in class A. This will lead to CircularReferencesDetectedException. Because there exist many objects (> 5.000) my VS debugger nearly hangs during debug session because of so much exceptions. Run application without debugger will just be fine.

Have I missed a configuration parameter? Why thinks my graph has circular references, which is not the case? Does not other implementation exist with avoiding Exceptions?

**Comment by Mike-EEE** [comment] 2017-09-29 12:53
Whoaaaaaaa... are you able to work around this for the time being by turning off exception messages in the output window?

And to be sure, you have enabled references by calling the `EnableReferences` method during the container configuration, correct?

If we cannot turn off those messages, I might have to consider another design here.

**Comment by thomasjoscht** [comment] 2017-09-29 13:21
I'm just calling `new ConfigurationContainer().EnableReferences().Create()` for creation of IExtendedXmlSerializer. Without calling `EnableReferences()` the exceptions will not be catched automatically and my program doesn't work at all. I've tried several things to only EnableReferences on specific members, but problem still persists. The `CircularReferencesDetectedException` is a normal case for my scenario.

Currently my workaround is to comment out `throw new CircularReferencesDetectedException` in ReferenceAwareSerializers. Then everything works fine.

PS: My result XML has 26k lines and 2,3MB size. Big but not extremely.

**Comment by Mike-EEE** [comment] 2017-09-29 15:06
Ok, just making sure about your configuration setup, so you are indeed configured correctly.

My thought (more like hope lol) is that this is due to the csproj reference.  Now that you have it built (undoing the commenting of `throw new CircularReferencesDetectedException` that is 😄), try removing the csproj and referencing the bin/ExtendedXmlSerializer.dll directly from disk and see if this still occurs.

If it does, please try building it in Release mode and referencing that dll.

The concern here of course is if this will occur is regular nuget references.  If it only occurs when you are in debug and/or via a csproj reference, then not a big deal as having it happen when you reference it from a regular/nuget reference.

Please let me know if you have any questions around this.

**Comment by thomasjoscht** [comment] 2017-09-29 18:27
I've done some further tests. Referencing (debug) builded dll directly does also not work. Also removing ExtendedXmlSerializer project from solution does not work. 

At least I've tested 2.0.0 alpha 6 version from Nuget. With Nuget version problem does not happen. I think problem with VS Debugger lies on some settings in VS (only user code debugging or so on) because exception throw and caught does also happen in 2.0.0 alpha 6 because of same workflow. The only difference ist that VS does not log this with diagnostics tools and therefor does not (nearly) hanging because of lot work. The exceptions are not shown in events window of diagnostics tools.

But why is this exception really necessary in this case? I think my model does not have a circular reference. Instead there is used one object per reference from two other different objects, which should be a normal case by working with `EnabledReferences`. Or what do you think?

**Comment by Mike-EEE** [comment] 2017-09-29 18:44
Indeed, I think you are right with the Just My Code reference.  Since there is a pdb, it thinks it is "your" code and treats it as such.

You mention the Debug build generates the messages still.  Did you get a chance to try the Release build, by chance?  I think this will address the problem as there are no pdb's (or should not be 😄), and will avoid the issue that you are experiencing.

The exception is thrown whenever there is a circular reference detected.  By default we throw the exception.  When `EnableReferences` is called on the container, we keep track of the reference and emit it once, with subsequent occurrences of the reference being tagged with our `reference`/`entity` properties.

I guess at this point I am a little confused on your model, as with the original post above, it seems that Class B and C share a relationship that would cause this state.  I am not sure if you are able to provide a quick sample project to highlight the issue, but that would be valuable.  It would seem to me that this is operating as expected, only that you are running into messages caused by Visual Studio thinking that ExtendedXmlSerializer is "Just My Code" due to the existence of pdb files.  Compiling as release mode should take care of this.

If you feel there is a bug in how we are determining circular references, I am certainly more than happy to explore that with you as well.  I would probably need a quick sample project demonstrating the issue, however. 👼

**Comment by thomasjoscht** [comment] 2017-09-29 19:29
You are right. Changing build type to Release will solve this. Then the project could also be part of my solution (until new 2.0.0 alpha 7 ist published). I think builded as Release hides the exception from VS debugger.

I will create a sample scenario where this will happen. But it could take time to mid of next week because I'm little busy this weekend.

**Comment by Mike-EEE** [comment] 2017-09-29 21:28
OK cool.   We're all learning a lot here, for sure. :)  Sounds like we have you out of performance mayhem for now, which is the important part.

**Comment by thomasjoscht** [comment] 2017-10-03 10:59
Hey, I've created a MS Unit Test class for this problem. The reason why the exceptions occur, which will lead to the performance lag of debugger is that I use a class type multiple times in multiple properties. Have a look at Table class and Scripts properties of the sample. The exception hints to Connection which will be handled as Ref by ExtendedXmlSerializer.

```c#
// ReSharper disable once CheckNamespace
namespace XmlSerialization
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Serialization;
    using ExtendedXmlSerializer.Configuration;
    using ExtendedXmlSerializer.ExtensionModel.References;
    using ExtendedXmlSerializer.ExtensionModel.Xml;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class XmlSerializerPerformanceTests
    {
        [TestMethod]
        public void PerformanceTests()
        {
            // create package
            var package = new Package
            {
                Name = "TestPackage"
            };

            // create 5 connections
            for (var i = 1; i <= 5; i++)
            {
                package.Connections.Add(new Connection
                {
                    Name = "Connection" + i,
                    Definition = "Put connection string here"
                });
            }

            // create 1000 tables
            for (var i = 1; i <= 1000; i++)
            {
                var table = new Table
                {
                    Name = "Table" + i,
                    PreScript = new Script()
                    {
                        Connection = package.Connections[0], // each script needs one ref to connection saved in package,
                        Sql = "Some pre sql for " + i
                    },
                    UseScript = new Script()
                    {
                        Connection = package.Connections[1], // does not matter which connection is used
                        Sql = "Some use sql for " + i
                    },
                    PostScript = new Script()
                    {
                        Connection = package.Connections[2], // does not matter which connection is used
                        Sql = "Some post sql for " + i
                    }
                };

                // each table has 20 columns
                for (var j = 1; j <= 20; j++)
                {
                    table.Columns.Add(new Column
                    {
                        Name = table.Name + " Column" + j
                    });
                }

                package.Tables.Add(table);
            }

            // create serializer with references enabled
            var serializer = new ConfigurationContainer().EnableReferences().Create();

            var stopwatch = new Stopwatch();

            // SERIALIZE
            stopwatch.Start();
            var xml = serializer.Serialize(new XmlWriterSettings
            {
                Indent = true
            }, package);
            stopwatch.Stop();

            //  some static counting in ReferenceAwareSerializers by custom implementation. Have a look at bottom of this file.
            var exceptionsDuringSerialization = ExceptionCounter.Count;
            var serializationDuration = stopwatch.ElapsedMilliseconds;
            Trace.WriteLine("Serialization takes " + serializationDuration + " ms");
            ExceptionCounter.Reset();

            // DESERIALIZE
            stopwatch.Restart();
            var newPackage = serializer.Deserialize<Package>(xml);
            stopwatch.Stop();

            var exceptionsDuringDeserialization = ExceptionCounter.Count;
            var deserializationDuration = stopwatch.ElapsedMilliseconds;
            Trace.WriteLine("Deserialization takes " + serializationDuration + " ms");

            // ***************** RESULT **************************
            // Serialization and deserialization result ist correct (OK)!
            // There are 1000 exceptions during serialization.
            // There are 0 exceptions during deserialization.
            // Serialization duration is nearly 1218 ms in RELEASE
            // Deserialization duratoin is nearly 159 ms in RELEASE
            // Serialization duration is nearly 21224 ms in DEBUG (<- PROBLEM)
            // Deserialization duratoin is nearly 186 ms in DEBUG
            Assert.IsTrue(newPackage != null && exceptionsDuringSerialization == 1000 && exceptionsDuringDeserialization == 0);

            // NOTE: My observation is that BusinessObject inheritance does not matter.
            // BUT: Main problem is Scripts type (and therefore Connection!) used multiple times in Table object. (<- PROBLEM REASON)
        }
    }

    public class BusinessObject
    {
        public Guid Id { get; set; } = Guid.NewGuid();
    }

    public class Package //: BusinessObject
    {
        public List<Connection> Connections { get; set; } = new List<Connection>();

        [XmlAttribute]
        public string Name { get; set; }

        public List<Table> Tables { get; set; } = new List<Table>();
    }

    public class Script //: BusinessObject
    {
        public Connection Connection { get; set; } // <- WARN: This is the problem. Because Script uses Connection (which will be handled as Ref in XmlSerializier).

        public string Sql { get; set; }
    }

    public class Table //: BusinessObject
    {
        [XmlAttribute]
        public string Name { get; set; }

        public List<Column> Columns { get; set; } = new List<Column>();

        public Script PreScript { get; set; }

        // WARN: This is the problem. Removing UseScript and PostScript will hide the exceptions!
        public Script UseScript { get; set; }
        public Script PostScript { get; set; }
    }

    public class Column //: BusinessObject
    {
        [XmlAttribute]
        public string Name { get; set; }

        public string Type { get; set; }
    }

    public class Connection //: BusinessObject
    {
        [XmlAttribute]
        public string Name { get; set; }

        public string Definition { get; set; }
    }

    // Definition of exception counter used in ReferenceAwareSerializers class for counting exceptions.
    /*
    public static class ExceptionCounter
    {
        private static readonly object _syncRoot = new object();

        public static int Count { get; private set; }

        public static void Increment()
        {
            lock (_syncRoot)
            {
                Count++;
            }
        }

        public static void Reset()
        {
            lock (_syncRoot)
            {
                Count = 0;
            }
        }
    }
    */
}
```

**Comment by Mike-EEE** [comment] 2017-10-03 11:17
Awesome!  Thank you for taking the time to put this together.  I am in agreement with you that the references as shown here should not trigger what you are experiencing.  Now, before we do instance (runtime)-based reference checking (again, of which it doesn't appear we are encountering here), we do static circular reference checking.  This is done regardless of whether you have references enabled or not, and is done as a(n ironically) performance consideration as it is less expensive than instance-based reference checking.  I am guessing this is where the problem is.  If references are enabled, we can skip the static and go straight to instance-checking.

I wasn't able to get to any work for this repo this past weekend, unfortunately, but I am aiming to put some time into it later today.  I will check this out and let you know what I find. 👍

**Comment by Mike-EEE** [comment] 2017-10-03 15:54
OK @thomasjoscht I was able to use your test to duplicate the problem easily on my machine.  Unfortunately, it is difficult to write a test around this without a bunch of work.  But I did manage to put in a fix for now, essentially only throwing the exception once per serialization.  Please try pulling the latest code and verify that it is fixed on your machine.  Thanks again for pointing this out.

**Comment by thomasjoscht** [comment] 2017-10-03 16:33
Thanks @Mike-EEE, your patch seems to work. My app seems to work now in debug mode. Back to initial request of empty collections: A nuget alpha7 will be nice ;-)

**Comment by Mike-EEE** [comment] 2017-10-03 16:48
Hah!  Fair enough.  We were waiting to hear back on another issue, but plenty of time has passed.  @wojtpl2 please feel free to deploy Alpha 7 when you have the chance. 👍

**Comment by wojtpl2** [comment] 2017-10-04 13:07
I've published alpha7 https://www.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha7 
Thanks for your job!

**Comment by Mike-EEE** [comment] 2017-10-18 19:12
Alright, closing this issue now.  Please feel free to open a new one in case you still have any issue that remains.  Thanks again for your input, @thomasjoscht!

**Closed by Mike-EEE** 2017-10-18 19:12 UTC
