### ISSUE TITLE
Migration error or misunderstanding

### ISSUE THREAD

**Issue by madben2000** [wojtpl2/ExtendedXmlSerializer#178] opened 2018-04-10 11:39 UTC
Having following nested class structure serialized:
public class MainClass
{
public SubClass Foo {get;set;}
}

public class SubClass
{
public SubSubClass Bar {get;set;}
}

public class SubSubClass
{
public string Type {get;set;}
}

Now SubSubClass is changed (Type -> Name), SubSubClassMigration added.
Trying to deserialize with:
var serializer = new ConfigurationContainer().ConfigureType<SubSubClass>().AddMigration(new SubSubClassMigration())).Create();
var obj = serializer.Deserialize<MainClass>(xmlWithOldVersionOfSubSubClass);
This is throwing exception in MigrationExtensions. What am I doing wrong? Is that scenario of only changing a sub sub class not supported? Thanks in advance

**Comment by Mike-EEE** [comment] 2018-04-10 12:18
Hi @madben2000 thanks for writing in.  The migration story/functionality is something that was pulled in from v1, and we didn't really get to put much effort into it for v2.  I am not that familiar with it, but if you provide the code for the migration I could take a look into it when I get a chance.  Also, @wojtpl2 might be able to answer your question as he was the one that wrote the v1 version and has a better understanding of how it works and its supported scenarios. :)

**Comment by wojtpl2** [comment] 2018-04-10 12:26
Hi @madben2000 It should work. Please provide the code or whole example as pull request with failing test.

There is working example: 
https://github.com/wojtpl2/ExtendedXmlSerializer/tree/master/samples/ExtendedXmlSerializer.Samples/MigrationMap

**Comment by madben2000** [comment] 2018-04-11 06:10
@wojtpl2 , @Mike-EEE please see https://github.com/madben2000/ExtendedXmlSerializer Issue178Tests.cs

**Comment by Mike-EEE** [comment] 2018-04-12 10:04
Do you see anything obvious here, @wojtpl2 ?

**Comment by madben2000** [comment] 2018-04-16 12:01
@wojtpl2, @Mike-EEE Did my example help you? Any ideas/solutions?

**Comment by Mike-EEE** [comment] 2018-04-16 13:35
Ah yeah I was going to take a look into it after I heard back from @wojtpl2 (or didn't hear back, as the case may be 😆), @madben2000.  Since this is a v1 extension I am not too familiar with it.  I basically made sure that it worked and the tests passed for the migration over to v2.

If we don't hear anything end of day then I shall start probing around for you.  In the meantime, have you considered looking into XSLT, perhaps?  It's one of the very many reasons I prefer XML over JSON (or any other format for that matter :)), and it was made for this very scenario if I understand correctly.

**Comment by wojtpl2** [comment] 2018-04-16 20:36
I don`t have time this week. Maybe in next. I`ve seen the code and this
example should work. We have some bug in our code. This migration need to
be used in list and maybe it is the problem? Mike can you check?

**Comment by madben2000** [comment] 2018-04-17 05:13
@wojtpl2 If you give me a hint what you mean with 

> This migration need to be used in list and maybe it is the problem

then I could also try to debug it further

**Comment by Mike-EEE** [comment] 2018-04-17 06:29
OK Mr. @madben2000 I super appreciate your persistence/patience and apologize for the delay.  I just checked in a fix you should now be able to run those tests and maybe find the next problem 😆.  There were two issues, one of which was how we were creating subtrees from the migration, and then another from how migrations coordinated with references.  Good find on both!  Please get the latest from our preview feed and let us know how it treats you:
https://www.myget.org/F/wojtpl2/api/v3/index.json

**Comment by wojtpl2** [comment] 2018-04-17 10:06
@Mike-EEE Big thanks! 
Was my response helpful?

**Comment by Mike-EEE** [comment] 2018-04-17 13:19
Woohoo!  Glad to hear @madben2000.  😄 

@wojtpl2 indeed your point set me in the right direction.  We were supporting single elements but not entire trees... but we do now. 🤓 

Going to close this issue now.  If you have any additional unexpected behavior please feel free to open an issue here and we'll take a look at it.

**Closed by Mike-EEE** 2018-04-17 13:19 UTC
Labels: bug, question

**Comment by wojtpl2** [comment] 2018-04-27 07:14
This issue was released in version 2.1.3. Release notes: #162
