### ISSUE TITLE
Issue with `EnableMissingMemberHandling` and `List`

### ISSUE THREAD

**Issue by johanvergeer** [wojtpl2/ExtendedXmlSerializer#258] opened 2019-07-11 07:38 UTC
I use `EnableMissingMemberHandling` with a `Command` object. 

```csharp
public struct CapturedInfo
{
    public CapturedInfo(string name, uint line, uint position, Type type)
    {
        this.Name = name;
        this.Line = line;
        this.Position = position;
        this.Type = type;
    }

    public string Name { get; }
    public uint Line { get; }
    public uint Position { get; }
    public Type Type { get; }
}

internal sealed class Command : ICommand<IFormatReader>
{
    public CapturedInfo Captured { get; private set; }

    public void Execute(IFormatReader parameter)
    {
        var content = ContentsHistory.Default
            .Get(parameter)
            .Peek();

        var lineInfo = parameter.Get() as IXmlLineInfo;
        this.Captured = new CapturedInfo(
            IdentityFormatter.Default.Get(parameter),
            (uint)lineInfo.LineNumber,
            (uint)lineInfo.LinePosition,
            content.Current.GetType());

        if (parameter.Identifier != "http://www.w3.org/2000/xmlns/")
        {
            parameter.Content();
        }

        using (var w = File.AppendText(Path.Combine(Path.GetTempPath(), "uniforms-serilize.log")))
        {
            this.Log(this.Captured, w);
        }
    }

    public void Log(CapturedInfo info, TextWriter w)
    {
        w.Write(DateTime.Now.ToString("MM/dd/yyyy HH:mm") + "; ");
        w.Write($@"Line: {info.Line}; ".PadRight(11, ' '));
        w.WriteLine($@"Position: {info.Position}; ".PadRight(14, ' '));
        w.WriteLine($@"    Name: {info.Name}; ");
        w.WriteLine($@"    Type: {info.Type}; ");
    }
}
```

A simple Foo class:

```csharp
public class Foo
{
    public Guid Identifier { set; get; }
}
```

And a serializer:

```csharp
var command = new Command();

var configuration = new ConfigurationContainer()
        .EnableReaderContext()
        .EnableMissingMemberHandling(command.Execute)
        .EnableMemberExceptionHandling()
        .UseOptimizedNamespaces()

        .ConfigureType<Foo>()

        .Create();
```

## Test without list

```csharp
var foo = new Foo { Identifier = Guid.NewGuid() };

var serializedFoo = serializer.Serialize(foo);
var deserializedFoo = serializer.Deserialize<Foo>(serializedFoo);

deserializedFoo.Should().BeEquivalentTo(foo);
```

test passes

## Test with list but without .EnableMissingMemberHandling(command.Execute)

I remove `.EnableMissingMemberHandling(command.Execute)` from the `ConfigurationContainer`

```csharp
var list = new List<Foo> {
    new Foo { Identifier = Guid.NewGuid() }
};

var serialized = serializer.Serialize(list);
var deserialized = serializer.Deserialize<List<Foo>>(serialized);

deserialized.Should().BeEquivalentTo(list);
```

Test passes

## Test with list and .EnableMissingMemberHandling(command.Execute)

I add `.EnableMissingMemberHandling(command.Execute)` back to the `ConfigurationContainer` and run the previous test.

### Serialization

The object is serialized as expected

```xml
<?xml version="1.0" encoding="UTF-8"?>
<List xmlns="https://extendedxmlserializer.github.io/system" exs:arguments="ns1:Foo" xmlns:exs="https://extendedxmlserializer.github.io/v2" xmlns:ns1="clr-namespace:Common.Unittests.Serialization;assembly=Common.Unittests">
  <Capacity>4</Capacity>
  <ns1:Foo>
    <Identifier>ff942bc3-6059-4fe6-b2e4-c17521c5b461</Identifier>
  </ns1:Foo>
</List>
```

### Deserialization

This is where it goes wrong.

The deserialized list contains the `Foo` object, but the properties are not set. 

The log created by `.EnableMissingMemberHandling(command.Execute)`:

```
07-11-2019 09:35; Line: 2;   Position: 7;  
    Name: http://www.w3.org/2000/xmlns/:ns1; 
    Type: System.Collections.Generic.List`1[Common.Unittests.Serialization.Foo]; 
07-11-2019 09:35; Line: 2;   Position: 126; 
    Name: http://www.w3.org/2000/xmlns/:exs; 
    Type: System.Collections.Generic.List`1[Common.Unittests.Serialization.Foo]; 
07-11-2019 09:35; Line: 2;   Position: 181; 
    Name: https://extendedxmlserializer.github.io/v2:arguments; 
    Type: System.Collections.Generic.List`1[Common.Unittests.Serialization.Foo]; 
07-11-2019 09:35; Line: 2;   Position: 205; 
    Name: http://www.w3.org/2000/xmlns/:xmlns; 
    Type: System.Collections.Generic.List`1[Common.Unittests.Serialization.Foo]; 
07-11-2019 09:35; Line: 4;   Position: 4;  
    Name: clr-namespace:Common.Unittests.Serialization;assembly=Common.Unittests:Foo; 
    Type: System.Collections.Generic.List`1[Common.Unittests.Serialization.Foo]; 
```

**Comment by Mike-EEE** [comment] 2019-07-11 08:25
Ah yes indeed @johanvergeer this is what I was talking about with the different tricky scenarios with having to differentiate between member, list elements, and lists with members.

[You sunk my battleship](https://youtu.be/xJo1WVTjaB0). 😆

Now that you are taking control of the reading process, you will have to determine when to progress or not which is leading to your issue here.  The magic is held here:

```
if (parameter.Identifier != "http://www.w3.org/2000/xmlns/") // This is the condition for manually checking for a read.  This is what is causing the problem.
{
   parameter.Content(); // This is what forces a read.  

   // Btw, you can also do the following to read:
   // parameter.Get().To<System.Xml.XmlReader>().Read();
}
```

As I mentioned, this is not pretty -- and I am _totally_ not happy with this.  But it's what we have to work with outside of a major re-write of the reader (which I am currently attempting/doing with v3).

Part of the consideration here is that we're starting to wander off the beaten path of what EXS was intended to do, which is to serialize and deserialize .NET POCO object graphs, rather than validate documents and ensure integrity.

That is, the "happy path" is to take a .NET object and its graph, serialize it, and deserialize it some point back into a .NET object graph that resides in memory.  This process will not introduce unknown elements unless you have changed the object definition during that time, for which we have the [migration extension](https://github.com/wojtpl2/ExtendedXmlSerializer#deserialize-old-version-of-xml) for that scenario.

If you are having problems with unknown elements (which is technically an invalid document and should fail), one thing you could do is run the document through [an external schema](https://docs.microsoft.com/en-us/dotnet/standard/serialization/xml-schema-def-tool-gen) (.xsd) first to validate it before sending it to EXS.  You could then also use XSLT to repair the document before sending it to us as well.

Please let me know if you have further questions around this.  I will also further consider this scenario to see if there's something else we can employ to remedy the friction here, as well.

**Comment by Mike-EEE** [comment] 2019-07-11 13:17
> I will also further consider this scenario to see if there's something else we can employ to remedy the friction here, as well.

I've thought about it further, @johanvergeer. 😁

Luckily, we haven't deployed this to public nuget yet, so we can introduce some breaking changes.  I did some spelunking through all the pieces here, and all of them were internal, so I was able to make some changes to get a better implementation.  Although, it's not by much.  This area of the serializer is still pretty difficult to work with.

The implementation now works with `List<T>` ... however, it does not seem to want to work with unknown elements directly within a list, such as this (removing attributes for brevity/clarity):

```
<List>
   <Capacity>4</Capacity>
   <Foo>Doesn't Exist!</Foo>
   <ns1:Issue258Tests-Subject><Message>Hello World!</Message></ns1:Issue258Tests-Subject>
</List>
```

This now works, and results in a successful deserialization, however:

```
<List>
   <Capacity>4</Capacity>
   <ns1:Issue258Tests-Subject><Foo>Doesn't Exist!</Foo><Message>Hello World!</Message></ns1:Issue258Tests-Subject>
</List>
```

Please see this code for the implementation:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/9e77728eef3884061835a540b635f9371c0dd882/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue258Tests.cs#L18-L80

Since what it seems you are testing is not invalid content within lists, I am apt to avoid digging further into this until you or someone else pipes up about it.

FWIW, I have also renamed `EnableMissingMemberHandling` to `EnableUnknownContentHandling` to better reflect intent.

Finally, another improvement I made was to filter out `xmlns`-based attributes before calling your delegate.  You basically get called now when the whole chain (members and list elements) returns `false` when performing their reading.

Please get latest from the preview feed (clearing cache -- [we're looking into this btw](https://github.com/wojtpl2/ExtendedXmlSerializer/issues/259)) and let me know if you find any further problems around this.

**Comment by Mike-EEE** [comment] 2019-07-17 07:12
This has been deployed in `2.1.21`: https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let us know if you encounter any further issues/questions/concerns around this and we will do our best to assist you.

Closing for now. 👍

**Closed by Mike-EEE** 2019-07-17 07:12 UTC
Labels: bug
