### ISSUE TITLE
Problem with installing nuget package

### ISSUE THREAD

**Issue by pvlgk** [wojtpl2/ExtendedXmlSerializer#160] opened 2018-01-27 14:34 UTC
While trying to install nuget package I receive an error:
_Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'ExtendedXmlSerializer 2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0_	

I'am using Visual Studio 2015,

**Comment by Mike-EEE** [comment] 2018-01-27 19:36
Hm... sorry to hear you're experiencing problems here @pvlgk.  I just now tried to install it as a sanity test in my side project and it worked OK.  The only thing I can think of is that we're using .NET Standard 2.0, but I am pretty sure that works fine in Visual Studio 2015.  I am not as familiar with this, but maybe @wojtpl2 might be able to help you out here.

**Comment by ondrasvoboda** [comment] 2018-01-29 09:07
I have similar error in VS2017:
_You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework._

**Comment by Mike-EEE** [comment] 2018-01-29 09:14
Boo.  The only thing I can think of is that the library that I am installing mine into is a .NET Standard 2.0 library.  So there might be something with installing it into framework-based projects.  We'll look into this and hopefully have a new release for you soon.

**Comment by Mike-EEE** [comment] 2018-01-29 19:10
Just curious here... do you run into the same problem when installing our nuget package from our preview feed?
https://www.myget.org/F/wojtpl2/api/v3/index.json

**Comment by pvlgk** [comment] 2018-01-30 07:12
There is no problem with version 1.5. But any version above 2.0 causes problem described here.

**Comment by Mike-EEE** [comment] 2018-01-30 08:47
Hmmm... alright that sucks.  My recommendation at this point is to create a .NET Standard 2.0 class library in your project, add the published ExtendedXmlSerializer nuget package there, and then reference this project to your target application project(s).  That *should* work for you in the interim while we get this squared away.  Hopefully sometime today. 😄

**Comment by wojtpl2** [comment] 2018-01-30 09:43
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/ExtendedXmlSerializer.csproj#L12

We should change it to:
<TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
And use #if net45. 
Of course if we want to support .net 4.5.

**Comment by Mike-EEE** [comment] 2018-01-30 11:44
Ahhhh bummer!  I was under the impression that .NET Standard 2.0 supports 4.0 and above... turns out it is 4.6.1 and above:

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

 😦  😦  😦

**Comment by Mike-EEE** [comment] 2018-01-30 12:01
Alright... This actually isn't too bad.  In fact it "just works" without having to use the dreaded `ifdef`'s.  The only thing it is complaining about is the new `ISerializationSurrogateProvider` support from #161.  Let me think about this a bit...

**Comment by Mike-EEE** [comment] 2018-01-30 12:05
OK I am apt to create a new csproj called `ExtendedXmlSerializer.Integration` and put the `ISerializationSurrogateProvider` in there, along with any future functionality/extensions that are not found in 4.5.  That sound good, @wojtpl2?  The only downside is that it would require another nuget package, correct?

**Comment by Mike-EEE** [comment] 2018-01-30 12:18
Alright I have checked in a potential fix for this problem.  Please get latest and let me know how it looks to you along with any thoughts/concerns/feedback.

**Comment by AQuentin2033** [comment] 2018-01-30 13:58
I agree with @wojtpl2 I think multitageting is the right way to handle lower framework support.  Using 2 nuget packages is way uglier than a few #ifdef - sorry Mike

**Comment by Mike-EEE** [comment] 2018-01-30 14:13
Haha yeah?  I am in the minority here huh.  Not the first time. 😄  Keep in mind that you would not add a reference to both `ExtendedXmlSerializer` and `ExtendedXmlSerializer.Integration`, but simply `ExtendedXmlSerializer.Integration` (as it will auto-include `ExtendedXmlSerializer` for you).

Well I will say and admit that it seems a little overkill to step aside from one `#ifdef` (well actually two of them once you include the extensions call.  I guess I am preparing for the future, but as [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) states, that isn't something you should plan for. ;)

So I think the plan of action here is... bite the bullet and use the `ifdef`'s for now... but if there are additional ones that are required and they start building up, let's please create an integration project as outlined here and make sure we keep our code pretty. Please. 😄

**Comment by AQuentin2033** [comment] 2018-01-30 14:17
Actually in this particular case you could leave your code clean and create your own copy of ISerializationSurrogateProvider in the System.Runtime.Serialization namespace wrapped in an #56 

... just a thought

**Comment by Mike-EEE** [comment] 2018-01-30 15:01
The problem is that we do want to use .NET Standard2.0... `ISerializationSurrogateProvider` works fine for `.netcoreapp2.0`, too... go figure.

The other problem I am encountering is now that we have a net45 build, our tests (in net471) are picking up the net45 and not the netstandard2.0 (which is 4.6.1 and above).

I tried doing this:

```
  <ItemGroup>
    <ProjectReference Include="..\..\src\ExtendedXmlSerializer\ExtendedXmlSerializer.csproj">
        <TargetFramework>net471</TargetFramework>
    </ProjectReference>
  </ItemGroup>
```

... but no dice.  Any guidance/suggestions here would be greatly appreciated.

**Comment by AQuentin2033** [comment] 2018-01-30 15:06
unit tests in VS only look at the first framework in the list - so the order should be
`<TargetFrameworks>netstandard2.0;net45</TargetFrameworks>`

**Comment by AQuentin2033** [comment] 2018-01-30 15:23
Not sure I follow your first statement tho,
.netcoreapp2.0 and .net471 are both runtimes which support .netstandard 2.0.  So if the library includes a conditional compilation it will apply for any runtime which references it
what I was suggesting was to have in your library
```
#if NETSTANDARD2_0 == false
namespace System.Runtime.Serialization
{
    public interface ISerializationSurrogateProvider
    {
        object GetDeserializedObject(object obj, Type t);
        object GetObjectToSerialize(Object obj, Type t);
        Type GetSurrogateType(Type t);
    }
}
#endif 
```
This way if the library is complied with .netstandard2.0 it will not include it and use the one provided by the framework and if the library is compiled with .net45 it will include it and use this one.
This way both compile, the rest of the code remains identical and there is only 1 #if in its own out of the way file

**Comment by Mike-EEE** [comment] 2018-01-30 15:42
Right... I agree.  But what I am encountering is that if my `TargetFrameworks` in ExtendedXmlSerializer.csproj is such:

```
<TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
```

When ExtendedXmlSerializer.Tests.csproj resolves this, it chooses `net45` rather than `netstandard2.0`.  I have to configure `TargetFrameworks` in my ExtendedXmlSerializer.csproj as such to make this work:

```
<TargetFrameworks>netstandard2.0;net45;net471</TargetFrameworks>
```

**Comment by Mike-EEE** [comment] 2018-01-30 16:08
OK I have committed a new version with passing tests now in .NET4.5, .NET4.7.1, and .NET Core 2.0.  I am still perplexed about this issue I am experiencing and will create a new question on StackOverflow to see what's up.

@wojtpl2 we can deploy a new version to NuGet if you would like.  `2.0.2`?

**Comment by Mike-EEE** [comment] 2018-01-30 16:31
FWIW, StackOverflow opened here:
https://stackoverflow.com/questions/48526219/is-there-a-way-to-force-a-project-reference-to-net-standard-project-to-a-specif

Let's hope I don't get too many downvotes. 😉

**Comment by Mike-EEE** [comment] 2018-01-31 07:57
Woohoo!  We got an answer and I got a fix checked in, so now we only build .NET 4.5 and .NET Standard 2.0, and test (successfully) on .NET 4.5, .NET 4.7.1, and .NET Core 2.0. 😄

**Comment by AQuentin2033** [comment] 2018-01-31 09:01
Nice! Can you make that a new nuget package? I would like to try and add it into at least 1 project this week if I can

**Comment by Mike-EEE** [comment] 2018-01-31 09:17
I am thinking we will release something to the main feed today.  You can of course use the preview feed here, which has the latest built for you already:
https://www.myget.org/F/wojtpl2/api/v3/index.json

**Comment by Mike-EEE** [comment] 2018-02-01 06:50
Hey @wojtpl2 would it be possible to publish a new nuget today?  If I understand correctly, I actually have the keys to do this, correct?  The steps are:

1. Update all versions in all csproj files
2. Create tag.
3. Push with tags

Let me know and I will give this a shot. :)

**Comment by wojtpl2** [comment] 2018-02-01 07:39
You can see all thinks to change in commit: https://github.com/wojtpl2/ExtendedXmlSerializer/commit/300a0413584802879311e604dcb57e6b17948d50 

You have to change in all csproj:
`<VersionPrefix>2.0.1</VersionPrefix>`
`<Version>2.0.1</Version>`

And 
```xml
<PackageReleaseNotes>
 +* Nullable Structs Cause Exception if Converter is Not Found #157
 +* Deserialization issue #156
 +* Bad serialization of string in RTF format #150
 +* The type initializer for ExtendedXmlSerializer.ContentModel.Reflection.PartitionedTypeCandidates threw an exception. #147
 +* Readonly Fields #146
 +* Extended Dictionary Not Passed into Parameter Correctly #144
 +* Optional Double Parameter Not Passed in Correctly #143
 +* Compatibility with the standard XML Serializer attributes #135
 +* System.Reflection.AmbiguousMatchException is thrown #155
 +* The serializer for type 'System.Collections.ObjectModel.ReadOnlyCollection`1 could not be found. #152
 +* Null serialization creates Null node ignoring property name instead of using xsi:nil="true" #141
      </PackageReleaseNotes>
```
in ExtendedXmlSerializer.csproj
https://github.com/wojtpl2/ExtendedXmlSerializer/commit/300a0413584802879311e604dcb57e6b17948d50#diff-802233c775e8a749803978227a02cdb6R25

**Comment by Mike-EEE** [comment] 2018-02-01 10:11
Woohoo!  Looks like it worked:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let me know if there are any outstanding issues and if so, please bring them up in the thread here:
https://github.com/wojtpl2/ExtendedXmlSerializer/issues/162

Closing this issue as it has been resolved.

**Closed by Mike-EEE** 2018-02-01 10:11 UTC
Labels: bug, deployment
